<?php

/**
 * @file
 * Ting subsearch using Bibliotek.dk service.
 */

use GuzzleHttp\Client as HttpClient;
use GuzzleHttp\Exception\ClientException as GuzzleClientException;

// Load admin configuration.
module_load_include('inc', 'subsearch_bibdk', 'subsearch_bibdk.admin');

/**
 * Implements hook_ting_search_results().
 */
function subsearch_bibdk_ting_search_results($keys, $conditions, $results) {

  $messages = array();


  if ($results->numTotalObjects > 10 && $results->numTotalObjects < 100) {
    // If any of fiction or non fiction is empty we cannot do the calculation.
    // Simply exit for now.
    if (empty($results->facets['facet.genreCategory']->terms['nonfiktion'])
      || empty($results->facets['facet.genreCategory']->terms['fiktion'])) {
      return $messages;
    }
    $nonfiction = $results->facets['facet.genreCategory']->terms['nonfiktion'];
    $fiction = $results->facets['facet.genreCategory']->terms['fiktion'];

    // Less than half fiction of nonfiction.
    if (($nonfiction / 2) > $fiction) {
      $messages[] = 'execute bibdk search';

      $secondary_result = ting_search_do_secondary_search($keys, array(
        'agency' => 190101,
        'profile' => 'default',
      ));

      if ($secondary_result->numTotalObjects > 100) {
        $items = array();

        $number_of_records_to_show = 4;
        foreach ($secondary_result->collections as &$collection) {
          if ($number_of_records_to_show == 0) {
            continue;
          }
          else {
            $number_of_records_to_show--;
          }
          $build = ting_collection_view($collection, 'minimal');
          $items[] = drupal_render($build);
        }

        $msg = t('If you search for "!keys" on <a href="https://bibliotek.dk/da/search/work?search_block_form=!keys">bibliotek.dk</a> instead you will get !bibdk-num-results where some of them is the following: !examples',
          array(
            '!keys' => $keys,
            '!num-results' => $results->numTotalObjects,
            '!bibdk-num-results' => $secondary_result->numTotalObjects,
            '!examples' => theme('item_list', array('items' => $items)),
          ));
        $messages[] = '<div class="messages warning">' . $msg . '</div>';
      }
    }
  }
  return $messages;
}

/**
 * Implements hook_entity_info_alter().
 */
function subsearch_bibdk_entity_info_alter(&$entity_info) {
  $entity_info['ting_object']['view modes']['minimal'] = array(
    'label' => t('Minimal'),
    'custom settings' => TRUE,
  );
  $entity_info['ting_collection']['view modes']['minimal'] = array(
    'label' => t('Minimal'),
    'custom settings' => TRUE,
  );
}

function subsearch_bibdk_preprocess_ting_object(&$vars) {
  if (isset($vars['elements']['#view_mode']) && $vars['elements']['#view_mode'] == 'minimal') {
    $vars['content']['ting_title'][0]['#prefix'] = '<div>';
    $vars['content']['ting_title'][0]['#suffix'] = '</div>';
  }

}
