<?php

/**
 * @file
 * Ting subsearch using Bibliotek.dk service.
 */

use GuzzleHttp\Client as HttpClient;
use GuzzleHttp\Exception\ClientException as GuzzleClientException;

// Load admin configuration.
module_load_include('inc', 'subsearch_bibdk', 'subsearch_bibdk.admin');

/**
 * Implements hook_ting_search_results().
 */
function subsearch_bibdk_ting_search_results($keys, $conditions, $results) {

  $messages = array();


  if ($results->numTotalObjects > 10 && $results->numTotalObjects < 100) {
    // If any of fiction or non fiction is empty we cannot do the calculation.
    // Simply exit for now.
    if (empty($results->facets['facet.genreCategory']->terms['nonfiktion'])
      || empty($results->facets['facet.genreCategory']->terms['fiktion'])) {
      return $messages;
    }
    $nonfiction = $results->facets['facet.genreCategory']->terms['nonfiktion'];
    $fiction = $results->facets['facet.genreCategory']->terms['fiktion'];

    // Less than half fiction of nonfiction.
    if (($nonfiction / 2) > $fiction) {
      $messages[] = 'execute bibdk search';

      $secondary_result = ting_search_do_secondary_search($keys, array(
        'agency' => 190101,
        'profile' => 'default',
      ));

      if ($secondary_result->numTotalObjects > 100) {
        $items = array();

        $number_of_records_to_show = 4;
        foreach ($secondary_result->collections as &$collection) {
          if ($number_of_records_to_show == 0) {
            continue;
          }
          else {
            $number_of_records_to_show--;
          }
          $build = ting_collection_view($collection, 'minimal');
          $items[] = drupal_render($build);
        }

        $msg = t('If you search for "!keys" on <a href="https://bibliotek.dk/da/search/work?search_block_form=!keys">bibliotek.dk</a> instead you will get !bibdk-num-results where some of them is the following: !examples',
          array(
            '!keys' => $keys,
            '!num-results' => $results->numTotalObjects,
            '!bibdk-num-results' => $secondary_result->numTotalObjects,
            '!examples' => theme('item_list', array('items' => $items)),
          ));
        $messages[] = '<div class="messages warning">' . $msg . '</div>';
      }
    }
  }
  return $messages;
}

/**
 * Implements hook_entity_info_alter().
 */
function subsearch_bibdk_entity_info_alter(&$entity_info) {
  $entity_info['ting_object']['view modes']['minimal'] = array(
    'label' => t('Minimal'),
    'custom settings' => TRUE,
  );
  $entity_info['ting_collection']['view modes']['minimal'] = array(
    'label' => t('Minimal'),
    'custom settings' => TRUE,
  );
}



/**
 * Implements hook_field_formatter_info().
 */
function subsearch_bibdk_field_formatter_info() {
  return array(
    'ting_title_minimal' => array(
      'label' => t('Link to subsearch'),
      'field types' => array(
        'ting_title',
      ),
      'settings' => array(
        'link_type' => 'none',
        'prefix_type' => 'no',
      ),
    ),

    'ting_author_minimal' => array(
      'label' => t('Link to subsearch'),
      'field types' => array(
        'ting_author',
      ),
    ),
  );
}


/**
 * Implements hook_field_formatter_view().
 */
function subsearch_bibdk_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();


  foreach ($items as $delta => $item) {
    switch ($display['type']) {
      case 'ting_title_minimal':
        /*
         * This doesn't work due to the way objects gets cached at the
         * moment. Until that is fixed, link all objects to collections when
         * requested, the page will redirect to ting/object/X if there is only
         * one.
         */
        $type = 'ting_object';
        if ($display['settings']['link_type'] == 'collection') {
          $type = 'ting_collection';
        }

        // Only create the link if the object is available in the data well.
        $title = check_plain($entity->title);

        $element[$delta] = array(
          '#prefix' => '<h2 class="ting-object-minimal-title">',
          '#suffix' => '</h2>',
          '#markup' => $title,
        );

        break;

      case 'ting_author_minimal':
        $creators = array();
        foreach ($entity->creators as $i => $creator) {
          $creators[] = $creator;
        }
        $markup_string = '';
        if (count($creators)) {
          if ($entity->date != '') {
            $markup_string = t('By !author_link (@year)', array(
              '!author_link' => implode(', ', $creators),
              // So wrong, but appears to be the way the data is.
              '@year' => $entity->date,
            ));
          }
          else {
            $markup_string = t('By !author_link', array(
              '!author_link' => implode(', ', $creators),
            ));
          }
        }
        elseif ($entity->date != '') {
          $markup_string = t('(@year)', array('@year' => $entity->date));
        }
        $element[$delta] = array(
          '#markup' => $markup_string,
        );
        break;

    }
  }

  return $element;
}
