<?php

/**
 * @file
 * Translated search.
 */

// Load Field module hooks.
module_load_include('inc', 'subsearch_translate', 'subsearch_translate.admin');

/**
 * Implements hook_ting_search_results().
 */
function subsearch_translate_ting_search_results($keys = NULL, $conditions = NULL, $results) {

  $messages = array();

  // If no google api key is set we cannot translate.
  if (empty(variable_get('translated_suggestion_google_key', ''))) {
    return $messages;
  }

  // If any of fiction or non fiction is empty we cannot do the calculation.
  // Simply exit for now.
  if (empty($results->facets['facet.genreCategory']->terms['nonfiktion'])
  || empty($results->facets['facet.genreCategory']->terms['fiktion'])) {
    return $messages;
  }
  $nonfiction = $results->facets['facet.genreCategory']->terms['nonfiktion'];
  $fiction = $results->facets['facet.genreCategory']->terms['fiktion'];

  // Less than half fiction of nonfiction.
  if (($nonfiction/2) > $fiction) {

    // Do translation
    $translated_keys = subsearch_translate_suggest_translated_keys($keys);
    $suggested_result = ting_search_do_secondary_search($translated_keys);

    if($suggested_result->numTotalObjects > $results->numTotalObjects) {
      $suggestion = $translated_keys;
      $msg = t('The search for "!keys" gave !num-results hits. If you search for the English translation "<a href="/search/ting/!suggested-keys">!suggested-keys</a>" you will get !suggested-num-results hits. ', array(
        '!suggested-keys' => strtolower($suggestion),
        '!suggested-num-results' => $suggested_result->numTotalObjects,
        '!keys' => $keys,
        '!num-results' => $results->numTotalObjects,
      ));
      $messages[] = '<div class="messages warning">' . $msg . '</div>';
    }

  }
  return $messages;
}

function subsearch_translate_suggest_translated_keys($keys) {

  $url = 'https://www.googleapis.com/language/translate/v2';

  $params = [];
  $params['q'] = $keys;
  $params['key'] = variable_get('translated_suggestion_google_key', '');
  $params['source'] = 'da';
  $params['target'] = 'en';

  $options['query'] = $params;
  $options['maxTime'] = 300;
  $url = url($url, $options);
  $curl = new MicroCURL();
  $headers[] = "Accept: application/json";
  $curl->set_option(CURLOPT_HTTPHEADER, $headers);
  $result = json_decode($curl->get(array($url)));
  //dsm($result);
  $curl->close();

  if (!empty($result->data->translations[0]->translatedText)) {
    return $result->data->translations[0]->translatedText;
  }
}
